/** TIDECLOAK IMPLEMENTATION */

import {
  Button,
  Modal,
  ModalVariant,
  Progress,
  ProgressStep,
  ProgressStepper,
  Spinner,
  Stack,
  StackItem,
  Text,
  TextContent,
  TextVariants,
} from "@patternfly/react-core";
import type { ToggleIGAStatus } from "@keycloak/keycloak-admin-client/lib/resources/tideProvider";
import { useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { useAdminClient } from "../admin-client";

const POLL_INTERVAL_MS = 1000;

type IgaToggleProgressModalProps = {
  /** The uuid generated by the caller and sent with the toggleIGA POST. */
  jobId: string;
  realm: string;
  isOpen: boolean;
  /** Called once the run reaches a terminal `completed` state. */
  onComplete: () => void;
  /** Called when the user dismisses the modal (only available once terminal). */
  onClose: () => void;
};

type StepVariant = "default" | "success" | "info" | "pending" | "danger";

/**
 * Map a backend stage `status` onto a PatternFly ProgressStep variant.
 * The backend owns the stage list and its labels; we only translate status.
 */
function statusToVariant(status: string): StepVariant {
  switch (status) {
    case "done":
      return "success";
    case "running":
      return "info";
    case "failed":
      return "danger";
    case "pending":
    default:
      return "pending";
  }
}

export const IgaToggleProgressModal = ({
  jobId,
  realm,
  isOpen,
  onComplete,
  onClose,
}: IgaToggleProgressModalProps) => {
  const { adminClient } = useAdminClient();
  const { t } = useTranslation();

  const [status, setStatus] = useState<ToggleIGAStatus | null>(null);
  // Guard against firing onComplete more than once.
  const completedRef = useRef(false);
  // Keep the latest onComplete without restarting the poll when the parent
  // re-renders (it passes a fresh callback each render).
  const onCompleteRef = useRef(onComplete);
  onCompleteRef.current = onComplete;

  useEffect(() => {
    if (!isOpen) {
      return;
    }

    let cancelled = false;

    const poll = async () => {
      try {
        const next = await adminClient.tideAdmin.toggleIGAStatus({
          realm,
          jobId,
        });
        if (cancelled) {
          return;
        }
        setStatus(next);
        if (next.state === "completed" && !completedRef.current) {
          completedRef.current = true;
          onCompleteRef.current();
        }
        // Stop polling on any terminal state.
        if (next.state !== "running") {
          clearInterval(interval);
        }
      } catch {
        // Swallow transient poll errors; the awaited toggleIGA POST in the
        // parent is the authoritative success/failure signal. Keep polling.
      }
    };

    // Kick off immediately, then on an interval.
    void poll();
    const interval = setInterval(() => void poll(), POLL_INTERVAL_MS);

    return () => {
      cancelled = true;
      clearInterval(interval);
    };
  }, [isOpen, jobId, realm, adminClient]);

  const stages = status?.stages ?? [];
  const doneCount = stages.filter((s) => s.status === "done").length;
  const totalCount = stages.length;
  const isFailed = status?.state === "failed";
  const isTerminal = status != null && status.state !== "running";

  return (
    <Modal
      variant={ModalVariant.medium}
      title={t("igaToggleProgressTitle")}
      isOpen={isOpen}
      showClose={isTerminal}
      onClose={isTerminal ? onClose : undefined}
      // Only offer a Close button once the run is terminal so a user can
      // dismiss a failed (or completed) run; in-flight the modal is modal.
      actions={
        isTerminal
          ? [
              <Button
                key="close"
                variant="primary"
                onClick={onClose}
                data-testid="iga-progress-close"
              >
                {t("close")}
              </Button>,
            ]
          : []
      }
    >
      <Stack hasGutter>
        {totalCount > 0 && (
          <StackItem>
            <Progress
              aria-label={t("igaToggleProgressTitle")}
              value={doneCount}
              min={0}
              max={totalCount}
              measureLocation="outside"
              label={`${doneCount} / ${totalCount}`}
            />
          </StackItem>
        )}
        <StackItem>
          {totalCount === 0 && !isFailed ? (
            <TextContent>
              <Text component={TextVariants.p}>
                <Spinner size="md" /> {t("igaToggleProgressStarting")}
              </Text>
            </TextContent>
          ) : (
            <ProgressStepper isVertical>
              {stages.map((stage) => {
                const variant = statusToVariant(stage.status);
                const showCount =
                  typeof stage.total === "number" &&
                  stage.total > 0 &&
                  typeof stage.current === "number";
                return (
                  <ProgressStep
                    key={stage.id}
                    id={stage.id}
                    titleId={`${stage.id}-title`}
                    aria-label={stage.label}
                    variant={variant}
                    isCurrent={status?.currentStageId === stage.id}
                    icon={
                      stage.status === "running" ? (
                        <Spinner size="md" />
                      ) : undefined
                    }
                    description={
                      showCount
                        ? `${stage.current} / ${stage.total}`
                        : undefined
                    }
                  >
                    {stage.label}
                  </ProgressStep>
                );
              })}
            </ProgressStepper>
          )}
        </StackItem>
        {isFailed && (
          <StackItem>
            <TextContent>
              <Text
                component={TextVariants.p}
                className="pf-v5-u-danger-color-100"
              >
                {status?.error?.message ?? t("igaToggleProgressFailed")}
              </Text>
            </TextContent>
          </StackItem>
        )}
      </Stack>
    </Modal>
  );
};
