/** TIDECLOAK IMPLEMENTATION */

import {
  Button,
  Modal,
  ModalVariant,
  Progress,
  ProgressStep,
  ProgressStepper,
  Spinner,
  Stack,
  StackItem,
  Text,
  TextContent,
  TextVariants,
} from "@patternfly/react-core";
import type { ToggleIGAStatus } from "@keycloak/keycloak-admin-client/lib/resources/tideProvider";
import { useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { useAdminClient } from "../admin-client";
import {
  IgaToggleWarningDetail,
  type IgaCommitFailure,
} from "./igaToggleWarnings";

const POLL_INTERVAL_MS = 1000;

type IgaToggleProgressModalProps = {
  /** The uuid generated by the caller and sent with the toggleIGA POST. */
  jobId: string;
  realm: string;
  isOpen: boolean;
  /**
   * Structured per-CR failures from the toggle POST response body, when the run
   * finished `completed_with_warnings`. The polled status only carries a flat
   * `error.message`, so the caller (which sees the richer POST body) passes the
   * structured `commitFailures` here so the modal can render a clean list
   * instead of the raw string. Undefined while the run is still in flight or on
   * a clean completion.
   */
  commitFailures?: IgaCommitFailure[];
  /**
   * Called once the run reaches a terminal success state. `withWarnings` is
   * true when the terminal state is `completed_with_warnings` (some CRs left
   * pending) so the parent can keep the modal open for the user to read the
   * warning detail rather than auto-closing it.
   */
  onComplete: (withWarnings: boolean) => void;
  /**
   * Called when the user dismisses the modal. Available at any time, including
   * mid-run ("Run in background") — dismissing only stops the status poll; the
   * in-flight toggle POST continues and still fires its success/error toast.
   */
  onClose: () => void;
};

type StepVariant =
  | "default"
  | "success"
  | "info"
  | "pending"
  | "warning"
  | "danger";

/**
 * Map a backend stage `status` onto a PatternFly ProgressStep variant.
 * The backend owns the stage list and its labels; we only translate status.
 */
function statusToVariant(status: string): StepVariant {
  switch (status) {
    case "done":
      return "success";
    case "running":
      return "info";
    case "warning":
      return "warning";
    case "failed":
      return "danger";
    case "pending":
    default:
      return "pending";
  }
}

export const IgaToggleProgressModal = ({
  jobId,
  realm,
  isOpen,
  commitFailures,
  onComplete,
  onClose,
}: IgaToggleProgressModalProps) => {
  const { adminClient } = useAdminClient();
  const { t } = useTranslation();

  const [status, setStatus] = useState<ToggleIGAStatus | null>(null);
  // Guard against firing onComplete more than once.
  const completedRef = useRef(false);
  // Keep the latest onComplete without restarting the poll when the parent
  // re-renders (it passes a fresh callback each render).
  const onCompleteRef = useRef<(withWarnings: boolean) => void>(onComplete);
  onCompleteRef.current = onComplete;

  useEffect(() => {
    if (!isOpen) {
      return;
    }

    let cancelled = false;

    const poll = async () => {
      try {
        const next = await adminClient.tideAdmin.toggleIGAStatus({
          realm,
          jobId,
        });
        if (cancelled) {
          return;
        }
        setStatus(next);
        // Both `completed` and `completed_with_warnings` are terminal-success
        // states: the run finished and the modal should close. The warning
        // (left-pending CRs) is surfaced separately via the warning block below
        // and the parent's toggle toast.
        if (
          (next.state === "completed" ||
            next.state === "completed_with_warnings") &&
          !completedRef.current
        ) {
          completedRef.current = true;
          onCompleteRef.current(next.state === "completed_with_warnings");
        }
        // Stop polling on any terminal state.
        if (next.state !== "running") {
          clearInterval(interval);
        }
      } catch {
        // Swallow transient poll errors; the awaited toggleIGA POST in the
        // parent is the authoritative success/failure signal. Keep polling.
      }
    };

    // Kick off immediately, then on an interval.
    void poll();
    const interval = setInterval(() => void poll(), POLL_INTERVAL_MS);

    return () => {
      cancelled = true;
      clearInterval(interval);
    };
  }, [isOpen, jobId, realm, adminClient]);

  const stages = status?.stages ?? [];
  const doneCount = stages.filter((s) => s.status === "done").length;
  const totalCount = stages.length;
  const isFailed = status?.state === "failed";
  const hasWarnings = status?.state === "completed_with_warnings";
  const isTerminal = status != null && status.state !== "running";

  return (
    <Modal
      variant={ModalVariant.medium}
      title={t("igaToggleProgressTitle")}
      isOpen={isOpen}
      showClose
      onClose={onClose}
      // Always render an enabled, tabbable Close button (PatternFly's FocusTrap
      // requires at least one focusable node while the modal is open, and the
      // body is non-interactive). Dismissing mid-run only stops the status poll
      // and closes the modal; the toggle POST is already in flight / committed
      // server-side and its success/error toast still fires when it resolves.
      actions={[
        <Button
          key="close"
          variant="primary"
          onClick={onClose}
          data-testid="iga-progress-close"
        >
          {isTerminal ? t("close") : t("runInBackground")}
        </Button>,
      ]}
    >
      <Stack hasGutter>
        {totalCount > 0 && (
          <StackItem>
            <Progress
              aria-label={t("igaToggleProgressTitle")}
              value={doneCount}
              min={0}
              max={totalCount}
              measureLocation="outside"
              label={`${doneCount} / ${totalCount}`}
            />
          </StackItem>
        )}
        <StackItem>
          {totalCount === 0 && !isFailed && !hasWarnings ? (
            <TextContent>
              <Text component={TextVariants.p}>
                <Spinner size="md" /> {t("igaToggleProgressStarting")}
              </Text>
            </TextContent>
          ) : (
            <ProgressStepper isVertical>
              {stages.map((stage) => {
                const variant = statusToVariant(stage.status);
                const showCount =
                  typeof stage.total === "number" &&
                  stage.total > 0 &&
                  typeof stage.current === "number";
                return (
                  <ProgressStep
                    key={stage.id}
                    id={stage.id}
                    titleId={`${stage.id}-title`}
                    aria-label={stage.label}
                    variant={variant}
                    isCurrent={status?.currentStageId === stage.id}
                    icon={
                      stage.status === "running" ? (
                        <Spinner size="md" />
                      ) : undefined
                    }
                    description={
                      showCount
                        ? `${stage.current} / ${stage.total}`
                        : undefined
                    }
                  >
                    {stage.label}
                  </ProgressStep>
                );
              })}
            </ProgressStepper>
          )}
        </StackItem>
        {isFailed && (
          <StackItem>
            {/* Failure path: the polled status carries only a flat
                `error.message`. Present it as a single concise headline + a
                normalised one-line detail (the raw "WORD:ClassName:" prefix
                noise stripped) instead of dumping the raw string. */}
            <TextContent>
              <Text
                component={TextVariants.p}
                className="pf-v5-u-danger-color-100"
              >
                {t("igaToggleProgressFailed")}
              </Text>
            </TextContent>
            <IgaToggleWarningDetail
              message={status?.error?.message}
              tone="danger"
            />
          </StackItem>
        )}
        {hasWarnings && (
          <StackItem>
            {/* Warning path: prefer the structured per-CR `commitFailures`
                handed down from the caller (which sees the richer POST body);
                fall back to the polled flat `error.message` when structured
                data is not available. Either way render the tidy
                headline + capped list + collapsible Details composition. */}
            <IgaToggleWarningDetail
              commitFailures={commitFailures}
              message={status?.error?.message}
              tone="warning"
            />
          </StackItem>
        )}
      </Stack>
    </Modal>
  );
};
